--==========================================================================--
--                Tooling Node Runtime WorkspaceSerializer                  --
------------------------------------------------------------------------------
--   https://github.com/Bondpley/Tooling-Node-Runtime-WorkspaceSerializer   --
--                               By Bondpley                                --
--                                  v.1.3                                   --
--==========================================================================--

return {
    "CFrame", "Position", "Orientation", "Size", "Transparency", "Color", "BrickColor", "Material",
    "Anchored", "CanCollide", "Shape", "Locked", "CastShadow", "CanQuery", "CanTouch",
    "MaxForce", "MaxTorque", "Velocity", "RotVelocity", "Massless", "CustomPhysicalProperties",
    "Density", "Friction", "Elasticity", "FrictionWeight", "ElasticityWeight",
    "Reflectance", "Texture", "MeshId", "TextureID", "Scale", "Offset", "VertexColor",
    "MeshType", "RenderFidelity", "CollisionFidelity", "GlobalWind",
    "BackgroundColor3", "BackgroundTransparency", "TextColor3", "Text", "TextSize", "Font",
    "TextTransparency", "TextStrokeTransparency", "TextStrokeColor3", "TextWrapped",
    "TextScaled", "RichText", "BorderSizePixel", "BorderColor3", "SizeConstraint",
    "MaxVisibleGraphemes", "LineHeight", "TextXAlignment", "TextYAlignment", "TextTruncate",
    "FontFace", "AnchorPoint", "Rotation", "Visible", "Active", "AutoButtonColor", "Modal",
    "Selected", "Selectable", "SelectionImageObject", "ImageTransparency", "ImageColor3",
    "ScaleType", "SliceCenter", "TileSize", "ResampleMode", "ImageRectOffset", "ImageRectSize",
    "ImageContent", "ZIndex", "LayoutOrder", "ClipsDescendants", "FillDirection",
    "HorizontalAlignment", "VerticalAlignment", "Padding", "SortOrder", "AutomaticSize",
    "SoundId", "Volume", "Pitch", "Looped", "Playing", "TimePosition", "PlaybackSpeed",
    "EmitterSize", "Rate", "Lifetime", "SpreadAngle", "Rotation", "Speed",
    "Acceleration", "Drag", "VelocityInheritance", "LightColor", "Brightness", "Range",
    "Shadows", "Angle", "Face", "Faces", "Style",
    "MaxForce", "MaxTorque", "LimitsEnabled", "CurrentDistance", "CurrentAngle",
    "Active", "State", "Thickness", "Color", "Visible",
    "Value", "StringValue", "BoolValue", "NumberValue", "ObjectValue",
    "DockWidgetPluginGuiInfo", "Enabled", "ToolTip", "Cursor", "Image", "Text",
    "PivotOffset", "CFrame", "Transform", "RigidityEnabled", "CollisionGroup", 
    "CanCollide", "Mass", "IsGrounded", "NetworkOwnership", "RootPart",
    "CurrentCamera", "Screenshot", "QualityLevel",
}
